name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache maven
        uses: actions/cache@v2.1.3
        with:
          path: ~/.m2/repository
          key: maven_cache

      - name: Build with Gradle
        run: ./gradlew clean build
